{
	"main.error.users_notifications_not_found": "Звуковые уведомления пользователей не найдены.",
	
	"auth.error.incorrect_login_or_password": "Не верно указан логин или пароль.",
	"auth.error.not_auth_or_token_expired": "Вы не авторизованы или время жизни токена сессии подошло к концу.",
	"auth.error.you_already_auth": "Вы уже авторизированы.",
	"auth.error.creating_user": "Пользователь не создался в базе данных в таблице Users.",
	"auth.error.session_id_not_exists": "Уникальный идентификатор сессии не существует.",

	"auth.error.missing_fields": "Обнаружены незаполненные поля: {{fields}}.",
	"auth.error.user_with_email_already_exists": "Пользователь с почтовым адресом {{email}} уже существует.",
	"auth.error.user_with_phone_already_exists": "Пользователь с номером телефона {{phone}} уже существует.",
	"auth.error.session_id_not_exists_on_deleted_session": "Отсутствует идентификатор сессии пользователя (session={{session}}).",
	"auth.error.user_not_exists": "Пользователь не существует.",

	"photos.error.user_not_found": "Пользователь не найден.",
	"photos.error.sharp_avatar_path_not_found": "Не передан путь к сжатому аватару.",
	"photos.error.sharp_photo_path_not_found": "Не передан путь к сжатой фотографии.",
	"photos.error.sharp_photo_paths_not_found": "Сжатые фотографии не найдены.",
	"photos.error.delete_photo_path_not_found": "Не передан путь для удаления фотографии.",
	"photos.error.photo_not_found": "Изображение не найдено.",
	"photos.error.sharped_photo_with_error": "Возникла ошибка при сжатии изображений: {{errorMessage}}",
	"photos.error.photo_does_not_exist": "Изображение не найдено.",

	"files.error.message_id_not_found": "Не передан id сообщения.",
	"files.error.files_not_found": "Не переданы файлы.",
	"files.error.file_path_open_not_found": "Не передан путь для открытия файла.",
	"files.error.file_path_download_not_found": "Не передан путь для скачивания файла.",
	"files.error.file_not_found": "Файл не найден.",

	"friends.error.accept_friend_not_found": "Идентификатор принимаемого пользователя не передан.",
	"friends.error.subscribe_id_not_found": "Не существует подписки между текущим и добавляемым пользователем.",
	"friends.error.friendship_not_exist": "Дружбы между переданными пользователя не существует.",
	"friends.error.friend_id_not_found": "Информация о пользователе не найдена, возможно, это временный чат.",
	"friends.error.subscribed_id_not_found": "Не передан идентификатор пользователя, на которого происходит подписка.",
	"friends.error.unfollowed_id_not_found": "Не передан идентификатор пользователя, от которого происходит отписка.",
	"friends.error.followed_link_not_found": "Не существует подписки между текущим и отписываемым пользователем.",
	"friends.error.added_id_not_found": "Не передан идентификатор пользователя, которого принимаем в друзья.",
	"friends.error.left_to_subscribed_id_not_found": "Не передан идентификатор пользователя, которого оставляем в подписчиках.",
	"friends.error.deleted_id_not_found": "Не передан идентификатор пользователя, которого удаляем из друзей.",
	"friends.error.blocked_id_not_found": "Не передан идентификатор пользователя, которого блокируем.",
	"friends.error.unblocked_id_not_found": "Не передан идентификатор пользователя, которого разблокируем.",
	"friends.error.check_blocked_id_not_found": "Не передан идентификатор пользователя при проверке на его блокировку.",
	"friends.error.get_common_friends_id_not_found": "Не передан идентификатор пользователя при получении общих друзей.",

	"users.error.user_not_found": "Пользователь не найден.",
	"users.error.user_details_not_found": "Дополнительная информация о пользователе не найдена.",
	"users.error.notifications_settings_not_found": "Настройки уведомлений пользователя не найдены.",
	"users.error.user_id_not_found": "Идентификатор пользователя не передан.",
	"users.error.user_with_id_not_found": "Пользователь с id={{id}} не найден.",
	"users.error.edit_incorrect_data": "Обнаружены незаполненные поля: {{fields}}.",
	"users.error.edit_incorrect_format": "Неверный формат поля: {{field}}.",

	"messages.error.get_unread_messages": "Возникла ошибка при получении непрочитанных сообщений.",
	"messages.error.user_id_in_message_not_found": "Не передан Ваш уникальный идентификатор в объекте сообщения.",
	"messages.error.chat_id_in_message_not_found": "Не передан уникальный идентификатор чата в объекте сообщения.",
	"messages.error.message_id_not_found": "Не передан уникальный идентификатор сообщения.",
	"messages.error.empty_edit_message_without_files": "Ошибка при изменении сообщения. Оно не может быть пустым без прикрепленных файлов.",
	"messages.error.deleted_message_id_not_found": "Не передан уникальный идентификатор удаляемого сообщения.",
	"messages.error.your_already_delete_this_message": "Данное сообщение уже было Вами удалено.",

	"chats.error.chat_id_not_found": "Не передан уникальный идентификатор чата.",
	"chats.error.partner_id_not_found": "Не передан уникальный идентификатор собеседника.",
	"chats.error.partner_not_found": "Собеседник чата не найден.",
	"chats.error.deleted_chat_id_not_found": "Не передан уникальный идентификатор удаляемого приватного чата.",
	"chats.error.users_in_chat_not_found": "Пользователи в чате {{chat}} не найдены.",
	"chats.error.chat_not_found": "Чат с идентификатором {{chatId}} не найден.",

	"middleware.error.limit_file_size": "Файл слишком большой. Максимальный размер – {{maxSize}}МБ.",
	"middleware.error.limit_file_count": "Можно загрузить максимум {{maxCount}} файлов.",

	"socket.disconnecting": "В процессе отключения сокет соединения ({{reason}}).",
	"socket.socket_disconnected_with_reason": "Сокет с идентификатором соединения {{socketId}} отключился по причине: {{reason}}.",
	"socket.emit_handled": "[{{timestamp}}] | Событие {{type}} обработано на клиенте.",
	"socket.handshake_connection_successful": "Сокет-соединение готово для установки нового соединения.",
	"socket.session_done": "Проверка сессии в хранилище Redis успешно завершена.",
	"socket.stopped": "Сервер сокет соединения остановлен.",

	"socket.error.user_id_not_found": "Не передан идентификатор пользователя.",
	"socket.error.user_not_found": "Пользователь не существует.",
	"socket.error.disconnect": "Возникла ошибка при отключении пользователя: {{message}}.",
	"socket.error.emit_with_ack": "Произошла ошибка при попытке отправки события {{type}}: {{message}}",
	"socket.error.emit_broadcast_with_ack": "Произошла ошибка при попытке отправки всем пользователям, кроме себя, события {{type}}: {{message}}",
	"socket.error.emit_to_with_ack": "Произошла ошибка при попытке отправки события {{type}} конкретному пользователю: {{message}}",
	"socket.error.emit_broadcast_empty_response": "Сбой в работе сокет-соединения. Список подтвержденных обработок событий от клиентов пуст.",
	"socket.error.handle_event_on_client": "При обработке данного события {{type}} на клиенте возникла ошибка: {{message}}",
	"socket.error.sessions_not_match_or_exists": "При проверке сессии пользователя [sessionId={{sessionId}}] возникла ошибка. Вы не авторизованы или время жизни токена сессии подошло к концу.",
	"socket.error.engine_socket": "Не нормальное отключение сокета с кодом {{code}}.\nТекст ошибки: {{message}}.\nДополнительный контекст: {{context}}.",

	"database.start": "Соединение с базой данных успешно установлено.",
	"database.close": "Соединение с бд успешно закрыто.",
	"database.up_migrations.success": "Запуск миграций успешно завершен.",
	"database.down_migrations.success": "Откат миграций успешно завершен.",


	"database.error.close": "Закрытие соединения с базой данных завершилось не удачно.",
	"database.error.connect": "Соединение с базой данных завершилось с ошибкой",
	"database.error.migrations": "Возникла ошибка с транзакцией при выполнении миграций",
	"database.error.up_migrations": "Запуск миграций завершился с ошибкой:",
	"database.error.down_migrations": "Запуск откатов миграций завершился с ошибкой:",

	"repository.error.photo_not_found": "Фотография не найдена.",
	"repository.error.destroyed_row_not_found": "Удаляемая строка не найдена.",
	"repository.error.internal_db": "Произошла ошибка в репозитории {{repo}} метода {{method}}: ",

	"redis.connection_successfull": "Соединение с клиентом Redis успешно установлено.",
	"redis.start_to_work": "Клиент Redis готов к работе.",
	"redis.stopped": "Клиент Redis остановлен.",
	"redis.reconnection": "Клиент Redis переподключается...",
	"redis.ttl_update": "Время жизни в размере {{ttl}} для ключа {{key}} успешно обновлено в Redis.",
	"redis.new_pair_is_set": "Новая пара [{{key}}:{{value}}] успешно записана в Redis.",
	"redis.key_successfull_deleted": "Ключ [{{key}}] успешно удален из Redis.",

	"redis.error.client_connect": "Соединение с базой данных Redis завершилось не удачно: ",
	"redis.error.client_work": "Ошибка в работе клиента Redis: ",
	"redis.error.ttl_update": "Произошла ошибка при обновлении времени жизни записи с ключом [{{key}}] из Redis: {{message}}.",
	"redis.error.get_value": "Произошла ошибка при получении значения по ключу [{{key}}] из Redis.",
	"redis.error.setting_new_pair": "Произошла ошибка при записи новой пары [{{key}}:{{value}}] в Redis.",
	"redis.error.deleted_key": "Произошла ошибка при удалении ключа [{{key}}] из Redis.",

	"server_started": "Экземпляр сервера запущен на порту: {{port}} в режиме: {{mode}}.",
	"start_server_error": "Возникла ошибка при запуске экземпляра сервера",

	"error.unhandled_sync": "Не обработанная ошибка в синхронном коде: {{errorMessage}}",
	"error.unhandled_async": "Не обработанная ошибка в асинхронном коде: {{reason}} ({{promise}})",
	"error.initialize_i18n": "Возникла ошибка при инициализации пакета i18n.",

	"config.rate-limiter.error.session_id": "Слишком много запросов для вашей сессии. Пожалуйста, попробуйте позже.",
	"config.rate-limiter.error.ip": "Слишком много запросов с вашего IP адреса. Пожалуйста, попробуйте позже.",

	"backup_job_schedule.started": "Задача резервного копирования запущена.",
	"backup_job_schedule.spawn_new_process": "Запуск процесса резервного копирования...",
	"backup_job_schedule.stopped": "Задача резервного копирования остановлена.",
	"backup_job_schedule.process_killed": "Процесс резервного копирования был остановлен принудительно [pid={{pid}}].",
	"delete_unused_files_job_schedule.started": "Задача удаления неиспользуемых файлов проекта запущена.",
	"delete_unused_files_job_schedule.stopped": "Задача удаления неиспользуемых файлов проекта остановлена.",
	"delete_unused_files_job_schedule.finished": "Удалено {{count}} файлов.",
	"delete_unused_files_job_schedule.terminate": "Воркер [threadId={{threadId}}] удаления неиспользуемых файлов проекта принудительно остановлен.",
	"delete_unused_files_job_schedule.full_stop": "Воркер [threadId={{threadId}}] удаления неиспользуемых файлов проекта был остановлен с кодом ошибки {{code}}.",
	"delete_unused_files_job_schedule.success_stopped": "Задача удаления неиспользуемых файлов проекта успешно завершена.",
	"delete_unused_files_job_schedule.error": "Возникла ошибка при удалении неиспользуемых файлов проекта: {{error}}.",

	"errors.sequelize.database_error": "Ошибка базы данных",
	"errors.sequelize.validation_error": "Ошибка валидации:",
	"errors.sequelize.duplicate_entry": "Дублирующаяся запись:",
	"errors.sequelize.database_operation_failed": "Операция с базой данных не выполнена:",
	"errors.sequelize.foreign_key_constraint_failed": "Ошибка внешнего ключа",
	"errors.sequelize.database_timeout": "Превышено время ожидания базы данных",
	
	"process.close_server": "Сервер остановлен с кодом {{code}}.",
	"process.get_signal_before_close": "Получен сигнал {{signal}}, выполняется остановка сервера...",
	"process.error.close_server": "Произошла ошибка во время остановки сервера: {{error}}",

	"mermaid.error.invalid_path_or_method": "Неверный путь или метод",
	"main.error.diagram_file_not_found": "Файл диаграммы не найден",
	"diagram.client":"Клиент",
	"diagram.server":"Сервер",
	"diagram.not_found":"не найден"
}
